### ISSUE TITLE
2.3版本使用anaconda报不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by MgArcher** [myhub/tr#109]
报错信息如下：
(base) PS C:\CodeFiles\image\TR_ocr\tr-2.3.0> python .\demo.py
Traceback (most recent call last):
  File ".\demo.py", line 2, in <module>
    import tr
  File "C:\CodeFiles\image\TR_ocr\tr-2.3.0\tr\__init__.py", line 2, in <module>
    from .tr import *
  File "C:\CodeFiles\image\TR_ocr\tr-2.3.0\tr\tr.py", line 33, in <module>
    _libc = ctypes.cdll.LoadLibrary('./libtr.dll')
  File "C:\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。
(base) PS C:\CodeFiles\image\TR_ocr\tr-2.3.0> python
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

我在另一个电脑上不使用anaconda就不报错，请问这是什么问题引起的？

**Comment by myhub** [comment]
https://github.com/myhub/tr/issues/114
