### ISSUE TITLE
OSError: dlopen(./libtr.so, 6): no suitable image found ... unknown file type, first eight bytes: 0x7F ...

### ISSUE THREAD

**Issue by saidRaiss** [myhub/tr#113]
MacOS Catalina version 10.15.7
Anaconda environment
Python : 3.8.5
pip : 21.0.1
I installed tr-2.0.3 package using ```pip install https://github.com/myhub/tr/archive/2.3.0.zip```
When I tried
```python
import tr
```
I got this error:
```
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/saidraiss/Desktop/work/prod/server/models/extraction/tr/tr/__init__.py", line 2, in <module>
    from .tr import *
  File "/Users/saidraiss/Desktop/work/prod/server/models/extraction/tr/tr/tr.py", line 35, in <module>
    _libc = ctypes.cdll.LoadLibrary('./libtr.so')
  File "/Users/saidraiss/opt/anaconda3/envs/prodenv/lib/python3.8/ctypes/__init__.py", line 459, in LoadLibrary
    return self._dlltype(name)
  File "/Users/saidraiss/opt/anaconda3/envs/prodenv/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(./libtr.so, 6): no suitable image found.  Did find:
	./libtr.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
	/Users/saidraiss/Desktop/work/prod/server/models/extraction/tr/tr/libtr.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
```

**Comment by saidRaiss** [comment]
Requirements
> Windows 7+/Ubuntu 16.04/Ubuntu 18.04
> python2/python3，需要安装numpy
> Windows系统需要安装VC_redist.x64.exe
