### ISSUE TITLE
win10安装报错

### ISSUE THREAD

**Issue by ykallan** [myhub/tr#114]
`C:\ProgramData\Anaconda3\python.exe F:/xxx/code/工具类/本地ocr服务/ocr_server/main.py
Traceback (most recent call last):
  File "F:/xxx/code/工具类/本地ocr服务/ocr_server/main.py", line 1, in <module>
    import tr
  File "C:\ProgramData\Anaconda3\lib\site-packages\tr-2.3.0-py3.7.egg\tr\__init__.py", line 2, in <module>
    from .tr import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tr-2.3.0-py3.7.egg\tr\tr.py", line 33, in <module>
    _libc = ctypes.cdll.LoadLibrary('./libtr.dll')
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。`

请问这个问题是什么呢？我在本地已经安装了VC_redist.x64.exe
现在不能确定是什么原因

**Comment by ykallan** [comment]
我找到原因了 python装了64位系统，需要32位的python才行 QAQ

**Comment by myhub** [comment]
谢谢反馈，这个问题我自己一直没找到原因

**Comment by beeper00** [comment]
@myhub  我电脑最新一次更新之后再用也是抱这个错误，我上网查可能也是变成了64位什么的，希望大佬解决一下

**Comment by ppinklesh** [comment]
![win193](https://user-images.githubusercontent.com/43771398/118940766-a9213900-b96e-11eb-9317-96556a56fcaf.png)
I am facing this issue in the windows system. I also installed Python 32 bit but it didn't work. Plz help.
