### ISSUE TITLE
windows 10 ?

### ISSUE THREAD

**Issue by vgopinath** [myhub/tr#17]
Hi,
Does it work under windows 10?
downloaded the source and ran python setup.py install, successfully installed
but when trying to import tr, below error message, (check for this 'libtr.dll' entire system, not found

Traceback (most recent call last):

  File "<ipython-input-1-9b258e84f697>", line 1, in <module>
    import tr

  File "C:\ProgramData\Anaconda3\lib\site-packages\tr-1.3.0-py3.7.egg\tr\__init__.py", line 2, in <module>
    from .tr import *

  File "C:\ProgramData\Anaconda3\lib\site-packages\tr-1.3.0-py3.7.egg\tr\tr.py", line 22, in <module>
    _libc = ctypes.cdll.LoadLibrary(os.path.join(_BASEDIR, 'libtr.dll'))

  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)

  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 126] The specified module could not be found

Thanks

**Comment by vgopinath** [comment]
oh ok thanks..
