### ISSUE TITLE
install tr to python 3.10 error

### ISSUE THREAD

**Issue by chensdk** [myhub/tr#172]
Traceback (most recent call last):
  File "d:\python\ocr\tr-master\tr_01.py", line 1, in <module>
    import tr
  File "d:\python\ocr\tr-master\tr\__init__.py", line 2, in <module>
    from .tr import *
  File "d:\python\ocr\tr-master\tr\tr.py", line 33, in <module>
    _libc = ctypes.cdll.LoadLibrary('./libtr.dll')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'd:\python\ocr\tr-master\tr\libtr.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by myhub** [comment]
有个版本不支持Windows的
