### ISSUE TITLE
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by lbw1320028474** [myhub/tr#2]
安装成功后报一下错误，该如何解决呢？
环境：Window7 64位     Python3.7 64位

（OSError: [WinError 193] %1 不是有效的 Win32 应用程序。）
Traceback (most recent call last):
  File "G:/LBWGitSpace/tr/demo.py", line 1, in <module>
    import tr
  File "G:\LBWGitSpace\tr\tr\__init__.py", line 2, in <module>
    from .tr import *
  File "G:\LBWGitSpace\tr\tr\tr.py", line 18, in <module>
    _libc = ctypes.cdll.LoadLibrary(os.path.join(_BASEDIR, 'libtr.so'))
  File "D:\MyInstalSoft\Python372\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "D:\MyInstalSoft\Python372\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by myhub** [comment]
Windows下暂时建议先使用其自带的Linux系统WSL: https://docs.microsoft.com/en-us/windows/wsl/install-win10，也可以用虚拟机。

**Comment by myhub** [comment]
现在已经支持windows版本了
https://github.com/myhub/tr/tree/windows
