### ISSUE TITLE
Support ARM?

### ISSUE THREAD

**Issue by CalvinPaean** [myhub/tr#37]
Thanks for your great project. I tried your project on NVIDIA TX2, but it failed. Will you help support running on ARM?

**Comment by lstk520** [comment]
i have tried it on jetson nano also failed
`jetbot@jetson-4-3:~/Documents/tr$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import tr
  File "/home/jetbot/Documents/tr/tr/__init__.py", line 2, in <module>
    from .tr import *
  File "/home/jetbot/Documents/tr/tr/tr.py", line 32, in <module>
    _libc = ctypes.cdll.LoadLibrary(os.path.join(_BASEDIR, 'libtr.so'))
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/jetbot/Documents/tr/tr/libtr.so: cannot open shared object file: No such file or directory`
