### ISSUE TITLE
Mac OS 10.14.4 can't run test.py

### ISSUE THREAD

**Issue by jacoobwang** [myhub/tr#4]
Python Version: 2.7.10
--------------------------------------------------------------------------------------------
`python test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from tr import *
  File "/Users/wangyong7/python/tr/tr/__init__.py", line 2, in <module>
    from .tr import *
  File "/Users/wangyong7/python/tr/tr/tr.py", line 18, in <module>
    _libc = ctypes.cdll.LoadLibrary(os.path.join(_BASEDIR, 'libtr.so'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/wangyong7/python/tr/tr/libtr.so, 6): no suitable image found.  Did find:
	/Users/wangyong7/python/tr/tr/libtr.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
	/Users/wangyong7/python/tr/tr/libtr.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03`

**Comment by myhub** [comment]
I have only tested under Python3 with Ubuntu 16.04 and Ubuntu 18.04

I will install Mac OS in my VirtualBox and try to support Mac OS
