### ISSUE TITLE
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by mxHoward** [myhub/tr#98]
安装完成后运行test.py报错。
------
tr 2.3.0 https://github.com/myhub/tr
17842536839662259333
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import tr
  File "C:\Users\Mxhow\Desktop\kaizeli\OCR\tr\tr\__init__.py", line 2, in <module>
    from .tr import *
  File "C:\Users\Mxhow\Desktop\kaizeli\OCR\tr\tr\tr.py", line 248, in <module>
    init(0, 0, "ctpn.bin")
  File "C:\Users\Mxhow\Desktop\kaizeli\OCR\tr\tr\tr.py", line 140, in init
    _libc.tr_init(pid, id, c_ptr(model), arg)
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

**Comment by mxHoward** [comment]
运行环境：windows10系统，python3.8

**Comment by myhub** [comment]
谢谢反馈，这个BUG在Windows系统会出现。大概周末会修复

**Comment by myhub** [comment]
bug已修复

**Comment by lb815a** [comment]
遇到了类似的问题，求问问题是出在哪里了，解决方案是什么呢
